{
 "title": "Päänäkymä",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Viimeksi päivitetty",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "currentData",
     "query": "SELECT \"APo_t1\" FROM \"currentData\"",
     "select": [
      [
       { "params": [ "APo_t1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tämänhetkinen tuotto",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "currentData",
     "query": "SELECT \"APo_t1\" FROM \"currentData\"",
     "select": [
      [
       { "params": [ "APo_t1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Päivän tuotto",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "currentData",
     "query": "SELECT \"Etdy_ge1\" FROM \"currentData\"",
     "select": [
      [
       { "params": [ "Etdy_ge1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kumulatiivinen tuotto",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "currentData",
     "query": "SELECT \"Et_ge0\" FROM \"currentData\"",
     "select": [
      [
       { "params": [ "Et_ge0" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tämänhetkinen lämpötila",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "℃" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Invertteri",
     "measurement": "currentData",
     "query": "SELECT \"INV_T0\" FROM \"currentData\"",
     "select": [
      [
       { "params": [ "INV_T0" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Moduuli",
     "measurement": "currentData",
     "query": "SELECT \"T_MDU1\" FROM \"currentData\"",
     "select": [
      [
       { "params": [ "T_MDU1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tuotto",
   "type": "timeseries",
   "description": "Aurinkopaneelien tuotto valitulta ajalta.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Kokonaislähtöteho (AC)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "currentData",
     "query": "SELECT mean(\"APo_t1\") FROM \"currentData\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "E_Puse_t1" ], "type": "field" }
      ],
      [
       { "params": [ "E_Puse_t1" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Kokonaiskulutusteho",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "currentData",
     "query": "SELECT mean(\"E_Puse_t1\") FROM \"currentData\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "E_Puse_t1" ], "type": "field" }
      ],
      [
       { "params": [ "E_Puse_t1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lämpötilat",
   "type": "timeseries",
   "description": "Invertterin ja moduulin lämpötilat.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "℃" } },
   "targets": [
    {
     "alias": "Lämpötila (Invertteri)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "currentData",
     "query": "SELECT mean(\"INV_T0\") FROM \"currentData\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "E_Puse_t1" ], "type": "field" }
      ],
      [
       { "params": [ "E_Puse_t1" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Lämpötila (Moduuli)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "currentData",
     "query": "SELECT mean(\"T_MDU1\") FROM \"currentData\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "E_Puse_t1" ], "type": "field" }
      ],
      [
       { "params": [ "E_Puse_t1" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}