{
 "title": "Main view",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Last updated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "currentData",
     "query": "SELECT \"APo_t1\" FROM \"currentData\"",
     "select": [
      [
       { "params": [ "APo_t1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current production",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "currentData",
     "query": "SELECT \"APo_t1\" FROM \"currentData\"",
     "select": [
      [
       { "params": [ "APo_t1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily production",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "currentData",
     "query": "SELECT \"Etdy_ge1\" FROM \"currentData\"",
     "select": [
      [
       { "params": [ "Etdy_ge1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cumulative production",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "currentData",
     "query": "SELECT \"Et_ge0\" FROM \"currentData\"",
     "select": [
      [
       { "params": [ "Et_ge0" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current temperatures",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "℃" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Inverter",
     "measurement": "currentData",
     "query": "SELECT \"INV_T0\" FROM \"currentData\"",
     "select": [
      [
       { "params": [ "INV_T0" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Module",
     "measurement": "currentData",
     "query": "SELECT \"T_MDU1\" FROM \"currentData\"",
     "select": [
      [
       { "params": [ "T_MDU1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Production",
   "type": "timeseries",
   "description": "Production of the solar panels in the chosen time.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Total AC Output Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "currentData",
     "query": "SELECT mean(\"APo_t1\") FROM \"currentData\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "E_Puse_t1" ], "type": "field" }
      ],
      [
       { "params": [ "E_Puse_t1" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Total Consumption Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "currentData",
     "query": "SELECT mean(\"E_Puse_t1\") FROM \"currentData\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "E_Puse_t1" ], "type": "field" }
      ],
      [
       { "params": [ "E_Puse_t1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "description": "Inverter and module temperatures.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "℃" } },
   "targets": [
    {
     "alias": "Temperature (Inverter)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "currentData",
     "query": "SELECT mean(\"INV_T0\") FROM \"currentData\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "E_Puse_t1" ], "type": "field" }
      ],
      [
       { "params": [ "E_Puse_t1" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Temperature (Module)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "currentData",
     "query": "SELECT mean(\"T_MDU1\") FROM \"currentData\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "E_Puse_t1" ], "type": "field" }
      ],
      [
       { "params": [ "E_Puse_t1" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}